### ISSUE TITLE
nodejs 2.0的版本还不能用吗？

### ISSUE THREAD

**Issue by xbl** [WildDogTeam/wilddog-doc2#1]
使用会报错...
var hostRef = wilddog.database().ref();
                                     ^
TypeError: wilddog.database is not a function

```
// 链接野狗
var dogConfig = {
    authDomain: 'XXX.wilddog.com',
    syncURL: 'https://XXX.wilddogio.com'
};
wilddog.initializeApp(dogConfig);

var hostRef = wilddog.database().ref();
```

**Comment by slashthinking** [comment]
使用wilddog.sync()，而不是wilddog.database(); SDK 2.0已经可用了。
