### ISSUE TITLE
Android sdk 中jniLibs中只有 armeabi-v7a 下的 so文件，此so可以在多种cpu平台下运行

### ISSUE THREAD

**Issue by zhanghan0616** [WildDogTeam/wilddog-doc2#24]
Android sdk 中jniLibs中只有 armeabi-v7a 下的 so文件，此so可以在多种cpu平台下运行

**Comment by stackOverMind** [comment]
@zhanghan0616  我没明白问题是什么，如果可以的话把问题描述的更详细一些把。

**Comment by zhanghan0616** [comment]
在Android 系统上，每一个CPU架构对应一个ABI：armeabi，armeabi-v7a，x86，mips，arm64- v8a，mips64，x86_64。而在 野狗云 中 只提供了 armeabi-v7a目录对应的so库文件，如果将这个so库文件放在其他的目录下，能否只支持相应的cpu架构的手机正常运行。

**Comment by laufly** [comment]
@zhanghan0616 你使用的是哪端的api？Wilddog Video么？
